import '@/app/css/globals.css'
import type { Metadata } from 'next'
import { Montserrat, Unica_One, Inter } from 'next/font/google'
import localFont from 'next/font/local'
 
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})

const unicaOne = Unica_One({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable: '--font-unica-one',
})

const clashDisplay = localFont({
  src: './fonts/ClashDisplay-Regular.woff2',
  display: 'swap',
  variable: '--font-clash-display',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${unicaOne.variable} ${clashDisplay.variable} ${inter.variable}`}>
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
